name: Check struct sizes

on:
  pull_request:
    branches:
    - master

jobs:
  run:
    runs-on: ubuntu-20.04
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install \
            libxml-libxml-perl \
            libxml-libxslt-perl \
            ninja-build \
            python-jinja2
        pip install jinja2
    - name: Clone DFHack
      uses: actions/checkout@v2
      with:
        repository: dfhack/dfhack
        submodules: true
    - name: Back up old structures
      # exclude tools to ensure that new versions (from the PR) are used, for consistency
      run: rsync -av library/xml/ xml-old/ --exclude .git --exclude tools
    - name: Clone df-structures
      uses: actions/checkout@v2
      with:
        path: xml-new
    - name: Install new structures
      run: rsync -av xml-new/ library/xml/ --exclude .git
    - name: Configure DFHack
      run: |
        cmake \
          -S . \
          -B build-ci \
          -G Ninja \
          -D BUILD_PLUGINS:BOOL=OFF \
          -D BUILD_XMLDUMP:BOOL=ON \
          -D CMAKE_INSTALL_PREFIX="$PWD/install-ci"
    - name: Dump struct sizes (old)
      run: |
        rsync -av xml-old/ library/xml/ --exclude .git
        ninja -C build-ci clean xml-dump-struct-sizes
        ./build-ci/library/xml/tools/xml-dump-struct-sizes > sizes-old.txt
    - name: Dump struct sizes (new)
      run: |
        rsync -av xml-new/ library/xml/ --exclude .git
        ninja -C build-ci clean xml-dump-struct-sizes
        ./build-ci/library/xml/tools/xml-dump-struct-sizes > sizes-new.txt
    - name: Upload report
      uses: actions/upload-artifact@v2
      with:
        name: sizes
        path: sizes-*.txt
